//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 SDIViewSwitch.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW1                   101
#define IDD_FORMVIEW2                   102
#define IDD_FORMVIEW3                   103
#define IDD_DIALOG_SHOWSURFACEDOMAIN    104
#define IDR_HTML_PROJECTBACKTOPARAMETERDOMAIN 105
#define IDR_HTML_PROJECTTOPARAMETERDOMAIN 106
#define IDR_HTML_PROJECTIONTOPARAMETERDOMAIN 107
#define IDR_HTML_URVEINTERSECTION       108
#define IDR_HTML_URVEINTERSECTION1      110
#define IDR_HTML_URVEINTERSECTION2      112
#define IDR_HTML_GENERALBILINEARTRANSFORMATION 113
#define IDR_HTML_GENERALBILINEARTRANSFORMATIONDLG 114
#define IDR_HTML_ACTION_LEASTSQUARE     115
#define IDR_HTML_ACTION_LEASTSQUARE1    117
#define IDR_MAINFRAME                   128
#define IDR_SDIVIETYPE                  129
#define NO_FORMVIEW_IN_RIGHT_PANE_HORIZ_SPLITTER_VIEW 136
#define RIGHT_PANE_HORIZ_SPLITTER_VIEW  137
#define IDB_BITMAP1                     138
#define IDB_BITMAP2                     152
#define IDB_BITMAP3                     153
#define IDR_IMPORTRES1                  155
#define IDR_IMPORTRES2                  156
#define IDD_DIALOG1                     158
#define IDR_MENU1                       159
#define IDD_DIALOG2                     160
#define IDR_MENU2                       161
#define IDD_DIALOG3                     162
#define IDD_DIALOG4                     163
#define IDD_ProjectBackToParameterDomain 164
#define IDB_BITMAP4                     165
#define IDD_DIALOG5                     166
#define IDD_DIALOG6                     167
#define IDD_DIALOG7                     168
#define IDB_BITMAP5                     169
#define IDR_MENU3                       170
#define IDD_AreaPreserving              171
#define IDD_DIALOG9                     172
#define IDD_ActionsGeneral              172
#define IDD_TransformationsTAB          173
#define IDD_objViewerTab                174
#define IDD_MobiusTransTab              175
#define IDD_BilinearTransTab            176
#define IDD_QuadraticTransTab           177
#define IDD_GeneralBilinearTransTab     178
#define IDD_ActionsTab                  179
#define IDD_ActionsGeneralBilinear      180
#define IDD_ActionsBilinear             181
#define IDD_ActionRender                182
#define IDD_LeastSquareMethod           183
#define IDD_TSPLINE                     184
#define IDR_MENU4                       185
#define IDD_TSPLINE_PREIMAGE            186
#define IDD_LANDMARK                    187
#define IDD_CompositeMobiusTransTab     188
#define IDR_MENU5                       189
#define IDD_DIALOG_VECTORFIELD          190
#define IDD_RicciFlow                   191
#define IDD_Harmonic                    192
#define IDD_POLYOMINO1                  193
#define IDD_POLYOMINO                   194
#define IDD_INPUTINFORMATION            195
#define IDD_SETFACEAREA                 196
#define IDD_DIALOG8                     197
#define IDD_LEVY_LEASTSQUARE            198
#define IDD_MESH_SETCOLORS              199
#define IDD_TeichmullerMap              200
#define IDD_DIALOG_                     203
#define IDD_DIALOG_ConstrainedRegistration 204
#define IDR_MENU6                       206
#define IDD_DIALOG_EDGE_SUBDIVISION     207
#define IDD_POLYOMINO2                  210
#define IDD_DIALOG_DynamicQuasi         213
#define IDD_DIALOG_DATA_ANALYSIS        216
#define IDD_DIALOG_EDGESWAP             218
#define IDD_DIALOG_TOOTH                220
#define IDD_DIALOG_BOOLOPERATION        222
#define IDD_DIALOG_OCC                  226
#define IDD_DIALOG_ACIS                 228
#define IDD_DIALOG10                    230
#define IDC_RADIO1                      1000
#define IDC_LEVY_UNIFORM_BOUNDARY       1001
#define IDC_RADIO2                      1002
#define IDC_SLIDER1                     1003
#define IDC_SPIN1                       1004
#define IDC_SLIDER2                     1005
#define IDC_SPIN2                       1005
#define IDC_SPIN__COMPOSITE_UKNOT       1006
#define IDC_SPIN3                       1006
#define IDC_SLIDER4                     1007
#define IDC_SPIN4                       1007
#define IDC_SLIDER6                     1008
#define IDC_SPIN5                       1008
#define IDC_SPIN__COMPOSITE_VKNOT       1009
#define IDC_SLIDER5                     1010
#define IDC_SPIN__COMPOSITE_SKNOT       1011
#define IDC_EDIT_NAME                   1012
#define IDC_CHECK6                      1013
#define IDC_SLIDER7                     1014
#define IDC_SPIN__COMPOSITE_TKNOT       1015
#define IDC_EDIT_ADDRESS                1016
#define IDC_CHECK7                      1017
#define IDC_SLIDER8                     1018
#define IDC_SPIN__COMPOSITE_ALPHA       1019
#define IDC_EDIT_CITY                   1020
#define IDC_SLIDER_a1_                  1021
#define IDC_SLIDER9                     1022
#define IDC_SPIN__COMPOSITE_BETA        1023
#define IDC_EDIT_STATE                  1024
#define IDC_SLIDER_a2_                  1025
#define IDC_EDIT_ZIPCODE                1026
#define IDC_SLIDER_b1_                  1027
#define IDC_BUT_SUBMIT                  1028
#define IDC_SLIDER_b2_                  1029
#define IDC_EDIT_a1_                    1030
#define IDC_COMBO1                      1031
#define IDC_DYNAMICQUASI_COMBO          1031
#define IDC_EDIT_a2_                    1032
#define IDC_COMBOSELECT                 1033
#define IDC_SCROLLBAR1                  1034
#define IDC_EDIT_b1_                    1035
#define IDC_SCROLLBAR2                  1036
#define IDC_EDIT_b2_                    1037
#define IDC_Quadratic_Reparameterization_ 1038
#define IDC_Texture                     1039
#define ID_IsoParametric_Line           1040
#define ID_ZOOMALL                      1041
#define ID_UPDATE_TREECONTROL           1042
#define ID_Extract_FreeformTransformation 1043
#define ID_Extract_FreeformTransformation2 1044
#define ID_OPENMESH_CLEAR_VERTEX_SELECTION 1045
#define IDC_UNIFORM_REPARA              1046
#define IDC_BUTTON11                    1047
#define IDC_Orthogonalityweight         1048
#define IDC_BUTTON12                    1049
#define IDC_SLIDER3                     1050
#define IDC_SLIDER_Weight               1051
#define IDC_Mobius_Alpha                1052
#define IDC_Export_ControlPoints        1053
#define IDC_Bilinear_Alpha1             1054
#define IDC_Export_Iso_Eps              1055
#define IDC_Bilinear_Alpha2             1056
#define IDC_Export_Triangulation        1057
#define IDC_Bilinear_Beta1              1058
#define IDC_Export_Triangulation2       1059
#define IDC_MobiusTransformation        1060
#define IDC_ParameterDomain             1061
#define IDC_Bilinear_Beta2              1062
#define IDC_GenerateNewSurface          1063
#define ShowSkeleton                    1064
#define IDC_Quadratic_Alpha1            1065
#define IDC_ExportPovRay                1066
#define IDC_Quadratic_Alpha2            1067
#define IDC_GenerateNewSurface2         1068
#define IDC_QuadraticReparaofAnySurface 1069
#define IDC_Quadratic_Alpha3            1070
#define IDC_NavigateStartPosition       1071
#define IDC_StartNavigate               1072
#define IDC_Marching                    1073
#define IDC_LoadSkeleton                1074
#define IDC_Quadratic_Beta1             1075
#define IDC_ViewPointAnimation          1076
#define IDC_Quadratic_Beta2             1077
#define IDC_ShowColon                   1078
#define IDC_Quadratic_Beta3             1079
#define IDC_STARTVIEWPOSITION           1080
#define IDC_ENDVIEWPOSITION             1081
#define IDC_SHOWFRAME                   1082
#define IDC_SaveSkeleton                1083
#define IDC_ZoomAll                     1084
#define IDC_DELETE_ALL_OBJECTS          1085
#define IDC_AREAPRESERVE                1086
#define IDC_ShowConvexFunction          1087
#define IDC_Mobius_Beta                 1088
#define IDC_ShowCoordinateAxis          1089
#define IDC_Objects                     1090
#define IDC_SLIDERCHANGEKNOT            1091
#define IDC_ADDKNOT                     1092
#define IDC_SLIDERMOVESPEED             1093
#define IDC_BUTTON2                     1094
#define IDC_BUTTON_UP_POLYOMINO         1094
#define IDC_BUTTON_DATAANALYSIS_ADDTOSET 1094
#define IDC_BUTTON_ONEPOINTLANDMARK     1094
#define IDC_QUADRATICPARAMETERIZE       1095
#define IDC_BUTTON_USHAPE               1095
#define IDC_BUTTON_DOWN_POLYOMINO       1095
#define IDC_BUTTON_DATAANALYSIS_SAVEFILESET 1095
#define IDC_BILINEAR_PARAMETERIZE       1096
#define IDC_BUTTON_USHAPE_TRIAGULATED   1096
#define IDC_BUTTON_UP_POLYOMINO2        1096
#define IDC_BUTTON_DATAANALYSIS_LOADFILESET 1096
#define IDC_BUTTON_Venus                1097
#define IDC_BUTTON10                    1097
#define IDC_BUTTON_DOWN_POLYOMINO2      1097
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS 1097
#define IDC_SLIDERFOV                   1098
#define IDC_BUTTON_UP_POLYOMINO_BASE    1098
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_CNN 1098
#define IDC_LIST1                       1099
#define IDC_BUTTON_DOWN_POLYOMINO_BASE  1099
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_CNN_NORMALIZE 1099
#define IDC_LIST_CHOOSE_DATA            1100
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_COMPUTEDATA 1100
#define IDC_BUTTON_Sophie               1101
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_PRENEUTRAL 1101
#define IDC_Quadratic_Reparameterization 1102
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_PRENEUTRAL_FourLevel 1102
#define IDC_BUTTON_Terrain              1103
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_PRENEUTRAL_FourLevel2 1103
#define IDC_SURFACEINFORMATION          1104
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_CNN_MATLAB 1104
#define IDC_RICHEDIT21                  1105
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_IMAGE_CNN 1105
#define IDC_EDIT1                       1106
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC 1106
#define IDC_BUTTON3                     1107
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_READSAVEDMESH 1107
#define IDC_FITTINGSURFACE_NT           1108
#define IDC_BUTTON_LEFT_POLYOMINO       1108
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_GENERATEMORPHMESH 1108
#define IDC_BUTTON4                     1109
#define IDC_BUTTON_UPDATE_STEP_POLYOMINO 1109
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONICTEST 1109
#define IDC_BUTTON_DELETE_DUPLICATE_LANDMARK 1109
#define IDC_BUTTON5                     1110
#define IDC_BUTTON_LEFT_POLYOMINO2      1110
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_PRE 1110
#define IDC_FACE2STEP2                  1111
#define IDC_BUTTON_LEFT_POLYOMINO_BASE  1111
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_ITERATIONS 1111
#define IDC_ProjectToParameterDomain    1112
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_ITERATIONS_EDGESWAP 1112
#define IDC_FACE2STEP4                  1113
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_AFTER 1113
#define IDC_ReadViewPoint               1114
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_PRE_CDT 1114
#define IDC_FaceExample                 1115
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_ITERATIONS_CDT 1115
#define IDC_FaceExample2                1116
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_ITERATIONS_EDGESWAP_CDT 1116
#define IDC_BezierExampleStep1          1117
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_AFTER_CDT 1117
#define IDC_BezierExampleStep2          1118
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_CDT 1118
#define IDC_VENUS_STEP1                 1119
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_PRE_CDT2 1119
#define IDC_VENUS_STEP2                 1120
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_ITERATIONS_EDGESWAP_CDT_MOVE 1120
#define IDC_VENUS_STEP3                 1121
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_CDT2 1121
#define IDC_BUTTON_DATAANALYSIS_DATAANALYSIS_OPTIMALHARMONIC_CDT_EXAMPLE1 1121
#define IDC_READBSFFILE                 1122
#define IDC_READBSFFILE2                1123
#define IDC_BONESTEP2                   1124
#define IDC_CheckAreaPreserving         1125
#define IDC_Actions_GeneralBilinear_Bezier 1126
#define IDC_ROTATION_PARAMETERIZATION   1127
#define IDC_BONESTEP1                   1128
#define IDC_BUTTON_FACEMODEL            1129
#define IDC_BUTTON_EXAMPLE1             1130
#define IDC_BUTTON_EXAMPLE2             1131
#define IDR_MESHTYPE                    1290
#define IDC_Conformality                1291
#define IDC_ShowTexture                 1292
#define IDC_BUTTON6                     1293
#define IDC_BUTTON7                     1294
#define IDC_GENERAL_SLIDER1             1295
#define IDC_GENERAL_SLIDER2             1296
#define IDC_GENERAL_SLIDER3             1297
#define IDC_GENERAL_SLIDER4             1298
#define IDC_GENERAL_SLIDER5             1299
#define IDC_GENERAL_SLIDER6             1300
#define IDC_GENERAL_SLIDER7             1301
#define IDC_GENERAL_SLIDER8             1302
#define IDC_GENERAL_SLIDER9             1303
#define IDC_GENERAL_SLIDER10            1304
#define IDC_GENERAL_SLIDER11            1305
#define IDC_GENERAL_SLIDER12            1306
#define IDC_GENERAL_SLIDER13            1307
#define IDC_GENERAL_SLIDER14            1308
#define IDC_GENERAL_SLIDER15            1309
#define IDC_GENERAL_SLIDER16            1310
#define IDC_MeshAnimation               1311
#define IDC_FinalMesh                   1312
#define IDC_TransformationTAB           1313
#define IDC_TAB2                        1314
#define IDC_BUTTON8                     1315
#define IDC_e00                         1316
#define IDC_e01                         1317
#define IDC_e10                         1318
#define IDC_e11                         1319
#define IDC_f00                         1320
#define IDC_f01                         1321
#define IDC_FACE2STEP1                  1322
#define IDC_f10                         1323
#define IDC_TAB1                        1324
#define IDC_f11                         1325
#define IDC_IDC_Actions_GeneralBilinear_GenerateSubMesh 1326
#define IDC_g00                         1327
#define IDC_g01                         1328
#define IDC_g10                         1329
#define IDC_g11                         1330
#define IDC_h00                         1331
#define IDC_h01                         1332
#define IDC_h10                         1333
#define IDC_h11                         1334
#define IDC_Actions_GeneralBilinear_Optimization 1335
#define IDC_Orthogonality_Weight        1336
#define IDC_BILINEAR_OPTIMIZE           1337
#define IDC_Actions_GeneralBilinear_Optimization2 1338
#define IDC_Actions_GeneralBilinear_Plot 1339
#define IDC_GENERALBILINEAR_POVRAY      1340
#define IDC_BUTTON_CARTOP               1341
#define IDC_BUTTON_Face                 1342
#define IDC_BUTTON_Bone                 1343
#define IDC_DerivativeVectorField       1344
#define IDC_BUTTON_GeneralBilinearInitialValue 1345
#define IDC_BsplineFitting              1346
#define IDC_BsplineFittingOptimization  1347
#define IDC_CARTOPSTEP1                 1348
#define IDC_CARTOPSTEP2                 1349
#define IDC_READLANDMARK                1350
#define IDC_ConformalityOpt11           1351
#define IDC_READSURFACEWITH             1351
#define IDC_ConformalityOpt22           1352
#define IDC_READSURFACEPLANE            1352
#define IDC_CHECKCONFORMITY             1353
#define IDC_READLIONSURFACEWITHGRAPH    1353
#define IDC_LABEL_COMPOSITE_UKNOT       1354
#define IDC_COPYSELECTEDPOINTSTOANCHORPOINTS 1354
#define IDC_COMPOSITEREPARABEZIER       1355
#define IDC_SAVEANCHORPOINTS            1355
#define IDC_EDIT_COMPOSITE_UKNOT        1356
#define IDC_LANDMARK_COMPUTEMU          1356
#define IDC_FACECOMPOSITETRANSFORMATION 1357
#define IDC_LANDMARK_COMPUTEAREASTRETCH 1357
#define IDC_EDIT_COMPOSITE_VKNOT        1358
#define IDC_LANDMARK_COMPUTEMU_Registration 1358
#define IDC_LABEL_COMPOSITE_VKNOT       1359
#define IDC_LANDMARK_COMPUTEAREASTRETCH_Regitration 1359
#define IDC_SLIDER_COMPOSITE_UKNOT      1360
#define IDC_SLIDER_COMPOSITE_VKNOT      1361
#define IDC_SLIDER_COMPOSITE_SKNOT      1362
#define IDC_EDIT_COMPOSITE_SKNOT        1363
#define IDC_LABEL_COMPOSITE_SKNOT       1364
#define IDC_SLIDER_COMPOSITE_TKNOT      1365
#define IDC_EDIT_COMPOSITE_TKNOT        1366
#define IDC_LABEL_COMPOSITE_TKNOT       1367
#define IDC_SLIDER_COMPOSITE_ALPHA      1368
#define IDC_EDIT_COMPOSITE_ALPHA        1369
#define IDC_LABEL_COMPOSITE_ALPHA       1370
#define IDC_SLIDER_COMPOSITE_BETA       1371
#define IDC_EDIT_COMPOSITE_BETA         1372
#define IDC_LABEL_COMPOSITE_BETA        1373
#define IDC_BUTTON_COMPOSITE_MOBIUS_UPDATE 1374
#define IDC_BUTTON_GENERATE_COMPOSITESURFACE 1375
#define IDC_LeastSquareMethod           1376
#define IDC_TEST                        1377
#define IDC_hierarchical_TESSELLATION   1378
#define IDC_CHECK_FIXBOUNDARY           1379
#define IDC_FITTINGSURFACE_NS           1380
#define IDC_LeastSquareMethod_Seperate  1381
#define IDC_AnimationSequence           1382
#define IDC_START                       1383
#define IDC_END                         1384
#define IDC_BUTTON1                     1385
#define IDC_BUTTON_ADDVERTEX            1386
#define IDC_BUTTON13                    1386
#define IDC_BUTTON9                     1387
#define IDC_BUTTON_KDTREE               1388
#define IDC_BUTTON14                    1388
#define IDC_LEVY_LEAST_SQUARE           1389
#define IDC_BUTTON15                    1389
#define IDC_BUTTON_TEICHMULLER          1390
#define IDC_BUTTON16                    1390
#define IDC_BUTTON_LOADTEST             1391
#define IDC_TSPLINE_SIMPLIFICATION      1392
#define IDC_BUTTON_GENERATEGEOGIAGEBOUNDARY 1393
#define IDC_BUTTON_ADDEDGE              1394
#define IDC_BUTTON_GENERATEGEOGIAGEHYBRID 1395
#define IDC_BUTTON_KDTREE_ITERATION     1396
#define IDC_BUTTON_STREIGHTENLANDMARK   1397
#define IDC_BUTTON_LOADEXAMPLEWITHSINGULARITY 1398
#define IDC_GENERATELANDMARKS           1399
#define IDC_BUTTON_STREIGHTENLANDMARK2  1400
#define IDC_TIMESLIDER                  1401
#define IDC_BUTTON_STREIGHTENLANDMARK3  1402
#define IDC_Omino_SetCurrentMesh        1403
#define IDC_BUTTON_STREIGHTENLANDMARK4  1404
#define IDC_BUTTON_HARMONIC             1405
#define IDC_Omino_SPLITLANDMARK         1406
#define IDC_BUTTON_STREIGHTENLANDMARK5  1407
#define IDC_Polyomino_Rectification     1408
#define IDC_BUTTON_STREIGHTENLANDMARK6  1409
#define IDC_Polyomino_Mesh_FixVertices  1409
#define IDC_Continue                    1410
#define IDC_Polyomino_Mesh_FixVertices2 1410
#define IDC_BUTTON_STREIGHTENLANDMARK7  1411
#define IDC_Polyomino_Mesh_FixVertices3 1411
#define IDC_CHECK1                      1412
#define IDC_Polyomino_Mesh_FixVertices4 1412
#define IDC_DynamicQuasi_ShowInitialConvexPara 1412
#define IDC_BUTTON_STREIGHTENLANDMARK8  1413
#define IDC_Polyomino_Mesh_SharpeVertex_Save 1413
#define IDC_DynamicQuasi_ShowInitialTargetPara 1413
#define IDC_SplitDirectionCHECK1        1414
#define IDC_DynamicQuasi_ShowIntermediateTargetPara 1414
#define IDC_BUTTON_STREIGHTENLANDMARK9  1415
#define IDC_Polyomino_Mesh_SharpeVertex_Load 1415
#define IDC_DynamicQuasi_ShowIndex      1415
#define IDC_HARMONIC_BOUNDARY_UNIFORM   1416
#define IDC_DynamicQuasi_ShowCircle     1416
#define IDC_BUTTON_LOADWORLDMAP         1417
#define IDC_Omino_SplitAngleSlider      1418
#define IDC_Polyomino_MergeSlope        1419
#define IDC_BUTTON_HARMONIC_ORIGINAL    1420
#define IDC_StopSequence                1421
#define IDC_BUTTON_HARMONIC_STRAIGHTENING 1422
#define IDC_BUTTON_SAVESIMPLIFIEDMFILE  1423
#define IDC_Omino_MergeAngleSlider      1424
#define IDC_EDITINPUTINFORMATION        1425
#define IDC_BUTTON_SAVESELECTEDLANDMARK 1426
#define IDC_EDITSETFACEAREA             1427
#define IDC_BUTTON_SAVESELECTEDPOINTS   1428
#define IDC_BUTTON_LOADSELECTEDPOINTS   1429
#define IDC_HARMONIC_BOUNDARY_CHORD     1430
#define IDC_BUTTON_SUBDIVIDE_EDGE       1431
#define IDC_Omino_LoadUSAMap            1432
#define IDC_EDIT_EDGE_SUBDIVISION       1433
#define IDC_EDITFACEAREA                1434
#define IDC_BUTTON_SEARCH_LANDMARK      1435
#define IDC_Polyomino_DeleteLandmark    1436
#define IDC_LEVY_TWOPOINT               1437
#define IDC_BUTTON_SEARCH_LANDMARK2     1437
#define IDC_BUTTON_SUBDIVIDE_EDGE_SLOPPING_HORIZONTAL 1438
#define IDC_ReadFile                    1439
#define IDC_BUTTON_SUBDIVIDE_EDGE_SLOPPING2 1440
#define IDC_BUTTON_SUBDIVIDE_EDGE_SLOPPING_VERTICAL 1441
#define IDC_Polyomino_SloppingEdgeSubdivision 1442
#define IDC_LEVY_CHORD_BOUNDARY         1443
#define IDC_HARMONIC_WEIGHTS_UNIFORM    1444
#define IDC_Omino_SloppingEdgeSubdivision 1445
#define IDC_TEICHMULLER_BOUNDARY_UNIFORM 1446
#define IDC_Omino_MergeSmallAngleSlider 1447
#define IDC_Polyomino_DeleteAuxillaryLandmarks 1448
#define IDC_Polyomino_FixPoints         1449
#define IDC_Polyomino_UnFixPoints       1450
#define IDC_Polyomino_CopyFixPoints     1451
#define IDC_Omino_LoadUSAStreighten     1452
#define IDC_UniformGrid_Initialization  1453
#define IDC_UniformGrid_Progessive_Mesh_Iteration 1454
#define IDC_Polyomino_ShortestPath      1455
#define IDC_Polyomino_Save_M_Landmark   1456
#define IDC_Polyomino_Save_M_Landmark2  1457
#define IDC_Polyomino_ExportLandmark    1458
#define IDC_Omino_LoadUSAStreighten2    1459
#define IDC_Omino_LoadGeorgiaMap        1460
#define IDC_Polyomino_AddVertexSelection 1461
#define IDC_Polyomino_AddEdgeSelection  1462
#define IDC_Omino_DataDrivenMorph       1463
#define IDC_Omino_DataDrivenMorphOptimization 1464
#define IDC_Polyomino_SetFaceArea       1465
#define IDC_Omino_SAVEFACEAREA          1466
#define IDC_Omino_LOADFACEAREA          1467
#define IDC_Omino_AddMergeConstraints   1468
#define IDC_Omino_SaveMergeConstraints  1469
#define IDC_Omino_LoadMergeConstraints  1470
#define IDC_Omino_LoadDebugInformation2 1471
#define IDC_Polyomino_CheckTriangulation 1472
#define IDC_Omino_LoadData              1473
#define IDC_Omino_LoadDebugInformation  1474
#define IDC_Omino_UniformGrid           1475
#define IDC_Omino_JianZhi               1476
#define IDC_Omino_LoadGeorgiaStreighten 1477
#define IDC_Omino_LoadIllinoisMap       1478
#define IDC_Omino_LoadIllinoisStreighten 1479
#define IDC_Polyomino_InverseLandmarkSelection 1480
#define IDC_Polyomino_InverseAllLandmarkStyle 1481
#define IDC_BUTTON_MESH_SETSHARPEDGECOLOR 1482
#define IDC_Polyomino_OpenMesh          1483
#define IDC_BUTTON_MESH_SETFACECOLOR    1484
#define IDC_BUTTON_MESH_SETEDGECOLOR    1485
#define IDC_Polyomino_TuteEmbedding     1486
#define IDC_ConstrainedRegistration_LoadFace 1487
#define IDC_ConstrainedRegistration_LoadFace2 1488
#define IDC_ConstrainedRegistration_ConstrainedHarmonic 1489
#define IDC_BUTTON_HARMONIC_HV_STRAIGHTENING 1490
#define IDC_ConstrainedRegistration_ConformalParameterization_Quad 1491
#define IDC_ConstrainedRegistration_LoadSophia 1492
#define IDC_ConstrainedRegistration_LoadSophia2 1493
#define IDC_ConstrainedRegistration_ChangeLandmarkIndex 1494
#define IDC_ConstrainedRegistration_SetMeshUV 1495
#define IDC_BUTTON_SetMeshUV_Mesh       1496
#define IDC_BUTTON_SetMeshUV_UV         1497
#define IDC_BUTTON_SetMeshUV_Mesh_Text  1498
#define IDC_BUTTON_SetMeshUV_UV_Text    1499
#define IDC_ConstrainedRegistration_LoadSophia_Holomorphic 1500
#define IDC_ConstrainedRegistration_SetMeshUV2 1501
#define IDC_ConstrainedRegistration_LoadSophia3 1502
#define IDC_ConstrainedRegistration_LoadExample2_Holomorphic 1503
#define IDC_ConstrainedRegistration_CopyVertexColor 1504
#define IDC_ConstrainedRegistration_ConformalParameterization_Circle 1505
#define IDC_ConstrainedRegistration_ConformalStraightening_Circle 1506
#define IDC_ConstrainedRegistration_LoadBrain 1507
#define IDC_ConstrainedRegistration_Brain_ConformalParameterization_Circle 1508
#define IDC_ConstrainedRegistration_ExtractBoundaryEdges 1509
#define IDC_ConstrainedRegistration_ConstrainedHarmonic_Sophia 1510
#define IDC_ConstrainedRegistration_LoadSophiaStraightening 1511
#define IDC_ConstrainedRegistration_LoadSophiaStraightening2 1512
#define IDC_ConstrainedRegistration_Brain_ConformalParameterization_Circle2 1512
#define IDC_ConstrainedRegistration_LoadBrain2 1513
#define IDC_ConstrainedRegistration_CopyVertexColor_DifferentTopology 1514
#define IDC_ConstrainedRegistration_LoadSophia_SearchStep 1515
#define IDC_ConstrainedRegistration_LoadSophiaStraightening3 1516
#define IDC_ConstrainedRegistration_Brain_ConformalParameterization_Circle3 1516
#define IDC_ConstrainedRegistration_MapRectangleToCircle 1517
#define IDC_ConstrainedRegistration_CopyVertexColor_DifferentTopology2 1518
#define IDC_ConstrainedRegistration_ConformalStraightening_Circle_Holomorphic 1519
#define IDC_ConstrainedRegistration_1627brain_strainghtening 1519
#define IDC_ConstrainedRegistration_CopyUV_DifferentTopology 1520
#define IDC_ConstrainedRegistration_LoadSophia_InitialRegistration_Harmonic 1521
#define IDC_ConstrainedRegistration_SetReferenceMesh 1522
#define IDC_ConstrainedRegistration_CopyUV_DifferentTopology2 1523
#define IDC_ConstrainedRegistration_TargetVertexColor_MU 1524
#define IDC_ConstrainedRegistration_LoadSophia_ConformalCircle 1525
#define IDC_ConstrainedRegistration_LoadSophia_Holomorphic2 1526
#define IDC_ConstrainedRegistration_MeshNormalization 1526
#define IDC_ConstrainedRegistration_ConformalStraightening_Rectangle_Holomorphic_Budata 1527
#define IDC_ConstrainedRegistration_ConformalParameterization_Circle_Holomorphic 1528
#define IDC_ConstrainedRegistration_LoadExample2_Budata 1529
#define IDC_ConstrainedRegistration_LoadExample2_Straightening 1530
#define IDC_ConstrainedRegistration_ConstrainedHarmonic_Budata 1531
#define IDC_ConstrainedRegistration_ConstrainedHarmonic_Budata_BijectiveRegistration 1532
#define IDC_ConstrainedRegistration_LoadExample2_Registration_Flip 1533
#define IDC_ConstrainedRegistration_ConformalStraightening_Circle_Budata_AN 1534
#define IDC_ConstrainedRegistration_ConformalStraightening_Circle_Budata_DI 1535
#define IDC_ConstrainedRegistration_ConformalStraightening_Circle_Budata_FE 1536
#define IDC_ConstrainedRegistration_ConformalStraightening_Circle_Budata_HA 1537
#define IDC_ConstrainedRegistration_ConformalStraightening_Circle_Budata_NE 1538
#define IDC_ConstrainedRegistration_ConformalStraightening_Circle_Budata_SA 1539
#define IDC_ConstrainedRegistration_ConformalStraightening_Circle_Budata_SU 1540
#define IDC_ConstrainedRegistration_LoadExample2_Budata2 1541
#define IDC_ConstrainedRegistration_LoadFeaturePoints 1542
#define IDC_BUTTON_DYNAMICHARMONIC      1543
#define IDC_ConstrainedRegistration_DeteleteFeaturePoints 1543
#define IDC_ConstrainedRegistration_LoadFeaturePoints_Landmark 1544
#define IDC_BUTTON_DYNAMICHARMONIC_Initialize 1545
#define IDC_ConstrainedRegistration_CopyImagetoSourceMesh 1545
#define IDC_ConstrainedRegistration_LoadExample2_Budata3 1546
#define IDC_BUTTON_DYNAMICHARMONIC_Iteration 1547
#define IDC_ConstrainedRegistration_SetNormalAsColor 1547
#define IDC_ConstrainedRegistration_ConformalStraightening_Circle_Budata_AN2 1548
#define IDC_BUTTON_DYNAMICHARMONIC_Iteration2 1549
#define IDC_ConstrainedRegistration_ConformalStraightening_Circle_Brain_ 1549
#define IDC_BUTTON_DYNAMICHARMONIC2     1550
#define IDC_ConstrainedRegistration_SetCurvaturelAsColor 1550
#define IDC_ConstrainedRegistration_ConformalStraightening_Circle_Budata_AN3 1551
#define IDC_BUTTON_DYNAMICHARMONIC_FREEOFFLIP 1552
#define IDC_ConstrainedRegistration_SetGaussCurvaturelAsColor 1552
#define IDC_ConstrainedRegistration_ConstrainedHarmonic_Sophia2 1553
#define IDC_BUTTON_MESH_SWAPSEQUENCE    1554
#define IDC_ConstrainedRegistration_CopyImagetoMesh 1554
#define IDC_ConstrainedRegistration_LoadExample2_Budata4 1555
#define IDC_BUTTON_MESH_MODIFYTOPOLOGY  1556
#define IDC_ConstrainedRegistration_SmoothGaussCurvature 1556
#define IDC_ConstrainedRegistration_LoadExample2_Budata5 1557
#define IDC_BUTTON_DYNAMICHARMONIC3     1558
#define IDC_ConstrainedRegistration_DetectTeetchLine 1558
#define IDC_BUTTON_LOADSELECTEDLANDMARK 1559
#define IDC_ConstrainedRegistration_SharpenGaussCurvature 1560
#define IDC_Polyomino_MergeSameStyle    1600
#define IDC_TEICHMULLER_BOUNDARY_CHORD  1601
#define IDC_SaveFile                    1602
#define IDC_Polyomino_DeleteSelectedLandmarks 1603
#define IDC_HARMONIC_WEIGHTS_LAPLACE    1604
#define IDC_Polyomino_MergeSeletedLandMarks 1605
#define IDC_Polyomino_ThreeConnected    1606
#define IDC_BUTTON_RICCIFLOW            1607
#define IDC_Polyomino_ClearLandMarkSelection 1608
#define IDC_HARMONIC_WEIGHTS_MEANVALUE  1609
#define IDC_Polyomino_InverseSeletedLandMarkStyle 1610
#define IDC_Polyomino_MergeSmall        1611
#define IDC_Polyomino_ExtendSmall       1612
#define IDC_BUTTON_TSPLINE_GEN          1613
#define IDC_Polyomino_SplitLandmarks    1614
#define IDC_Polyomino_SaveLandmark      1615
#define IDC_Polyomino_CurveStraight     1616
#define IDC_Polyomino_Save_Landmark     1617
#define IDC_Polyomino_LoadLandmark      1618
#define IDC_Polyomino_SmoothLandMarks   1619
#define IDC_Polyomino_SmoothSelectedLandMarks 1620
#define IDC_Polyomino_Triangulate       1621
#define IDC_Polyomino_ClearVertexSelection 1622
#define IDC_Polyomino_CheckInvalidEdges 1623
#define IDC_Polyomino_AddLandmark       1624
#define IDC_Polyomino_BackUpLandMarks   1625
#define IDC_Polyomino_SetAuxillaryLandmark 1626
#define IDC_Polyomino_AuxillaryVisiable 1627
#define IDC_Omino_SmallLandmarkLengthSlider 1628
#define IDC_Polyomino_CurveStraight_Selected 1629
#define IDC_BUTTON_SetMeshUV_Mesh_Polyomino 1630
#define IDC_BUTTON_SetMeshUV_UV_Polyomino 1631
#define IDC_BUTTON_SetMeshUV_Mesh_Text_Polyomino 1632
#define IDC_BUTTON_SetMeshUV_UV_Text_Polyomino 1633
#define IDC_BUTTON_COPYSELECTEDLANDMARKVERTEXPOSITION 1634
#define IDC_BUTTON_LOADFINALRECTILINEARMAP 1635
#define IDC_BUTTON_RIGHT_POLYOMINO      1636
#define IDC_EDIT_STEP_POLYOMINO         1637
#define IDC_BUTTON_LOAD_FIRSTUNIFORMGRID 1638
#define IDC_DYNAMIC_QUASI_LOAD3DSURFACE 1638
#define IDC_BUTTON_INITIALIZEUNIFORMGRID 1639
#define IDC_DYNAMIC_COMPUTEHARMONICENERGY 1639
#define IDC_BUTTON_CLEARSELECTEDSHARPEDGES 1640
#define IDC_DYNAMIC_CHECKDELAUNAY       1640
#define IDC_BUTTON_SetSourceSharpEdge   1641
#define IDC_DYNAMIC_QUASI_LOADTWOTRIANGLES 1641
#define IDC_BUTTON_SetTargetSharpEdge2  1642
#define IDD_DIALOG_DynamicQuasi_ConvexPara_Static 1642
#define IDC_BUTTON_MoveSourceToTarget   1643
#define IDD_DIALOG_DynamicQuasi_TargetPara_Static 1643
#define IDC_BUTTON_UpdateSharpStructure 1644
#define IDC_DYNAMIC_SETTARGETBOUNDARY   1644
#define IDC_BUTTON_SUBDIVIDESHARPEDGE   1645
#define IDC_DYNAMIC_SAVETARGETPARAMESH  1645
#define IDC_EDIT_NUM_POLYOMINO2         1646
#define IDC_DYNAMIC_LOADTARGETPARAMESH  1646
#define IDC_BUTTON_DeleteSelectedSharpEdges 1647
#define IDC_DYNAMIC_DYNAMICHARMONIC     1647
#define IDC_BUTTON_RIGHT_POLYOMINO2     1648
#define IDC_DYNAMIC_DYNAMICHARMONIC_MAPPINGSEQUENCES 1648
#define IDC_BUTTON_DeleteSelectedSharpEdges2 1649
#define IDC_SLIDER_DYNAMICQUASICONFORMAL_SLIDER 1649
#define IDC_BUTTON_DeleteSelectedSharpEdges3 1650
#define IDC_DYNAMICQUASICONFORMAL_SPIN  1650
#define IDC_BUTTON_DeleteSelectedSharpEdges4 1651
#define IDC_DYNAMICQUASI_EDIT           1651
#define IDC_BUTTON_Polyomino_GenerateNewPoint 1652
#define IDC_DYNAMIC_OPTIMALHARMONIC     1652
#define IDC_BUTTON_Polyomino_GenerateTwoPointLine 1653
#define IDC_BUTTON_DATAANALYSIS_LOADFIRST 1653
#define IDD_DIALOG_DynamicQuasi_ConvexPara_Static2 1653
#define IDC_BUTTON_Polyomino_GenerateNewPoint2Line 1654
#define IDC_BUTTON_DATAANALYSIS_LOADNEXT 1654
#define IDC_BUTTON_LOAD_FinalUNIFORMGRID 1655
#define IDC_BUTTON_DATAANALYSIS_LOADSETFIRST 1655
#define IDC_BUTTON_VisualizationPopulation 1656
#define IDC_BUTTON_DATAANALYSIS_LOADSETNEXT 1656
#define IDC_BUTTON_MIDDLECENTER         1657
#define IDC_EDIT_ZOOM_CENTER_VERTEX     1657
#define IDC_EDIT_NUM_POLYOMINO_MININDEX 1658
#define IDC_BUTTON_ZOOM_CENTERED_ATVERTEX 1658
#define IDC_EDIT_NUM_POLYOMINO_MAXINDEX 1659
#define IDC_BUTTON_SetMeshUV_DATAANALYSIS_Mesh 1659
#define IDC_BUTTON_AVERAGE_HORIZONTAL   1660
#define IDC_BUTTON_SetMeshUV_DATAANALYSIS_TARGET 1660
#define IDC_BUTTON_AVERAGE_VERTICAL     1661
#define IDC_BUTTON_SetMeshUV_Mesh_DATAANALYSIS_Text 1661
#define IDC_EDIT_NUM_POLYOMINO_PUZZLESIZE 1662
#define IDC_BUTTON_SetMeshUV_TARGET_DATAANALYSIS_Text 1662
#define IDC_BUTTON_ADDPUZZLE            1663
#define IDC_SLIDER_DATAANALYSIS_MORPH_SLIDER 1663
#define IDC_BUTTON_SAVEPUZZLE           1664
#define IDC_BUTTON_LOADPUZZLE           1665
#define IDC_EDIT_NUM_POLYOMINO_XNUMBER  1666
#define IDC_EDIT_NUM_POLYOMINO_YNUMBER  1667
#define IDC_BUTTON_RIGHT_POLYOMINO_BASE 1668
#define IDC_BUTTON_SETFACEPOINTS_SELECTED 1669
#define IDC_BUTTON_SETFACEPOINTS_DELETE 1670
#define IDC_BUTTON_SaveDeletedFaces     1671
#define IDC_BUTTON_SavePUZZLEPIECE      1672
#define IDC_BUTTON_SavePUZZLEPIECE2     1673
#define IDC_BUTTON_SavePUZZLEPIECE3     1674
#define IDC_BUTTON_CHECKPOINTWITHFIVEREGIONS 1674
#define IDC_BUTTON_LoadPUZZLEPIECE      1675
#define IDC_BUTTON_USRASTRERIZATION     1676
#define IDC_BUTTON_LOADCHINA            1677
#define IDC_BUTTON_SELECTLANDMARKS_TWOPOINTS 1677
#define IDC_BUTTON_LOADCHINA_TRIANGULATE 1678
#define IDC_BUTTON_AddLandmarks         1678
#define IDC_BUTTON_DETECT_OPENLANDMARK  1679
#define IDC_BUTTON_SUBDIVIDESHARPEEDGE  1680
#define IDC_BUTTON_SETALLLANDMARK_REGULAR 1681
#define IDC_BUTTON_DELETEDUPLICATEPOINTSINLANDMARK 1682
#define IDC_BUTTON_LOADCHINASTRAIGHTENED 1683
#define IDC_BUTTON_SAVEDATAFROMMESH     1684
#define IDC_BUTTON_LOADRECTILINEARMESH  1685
#define IDC_BUTTON_MODIFYRECTILINEAR3414 1686
#define IDC_BUTTON_MODIFYRECTILINEARMESH3350 1687
#define IDC_BUTTON_LoadFinalChinaPolyomino 1688
#define IDC_BUTTON_TOOTH_BOUNDARYDETECTION 1689
#define IDC_BUTTON_TOOTH_MESHSMOOTH     1690
#define IDC_BUTTON_TOOTH_LOADPATH       1691
#define IDC_BUTTON_TOOTH_DeleteSharpEdge 1692
#define IDC_BUTTON_BOOLOPERATION_INTERSECTIONCURVES 1692
#define IDC_BUTTON_TOOTH_AddSharpEdge2  1693
#define IDC_BUTTON_TOOTH_ClearSharpEdgeSelection 1694
#define IDC_BUTTON_TOOTH_SAVEPATH       1695
#define IDC_BUTTON_TOOTH_ClearSharpVertexSelectio 1696
#define IDC_BUTTON_TOOTH_DeleteSharpEdge_TwoPoints 1697
#define IDC_BUTTON_TOOTH_SwapEdge       1698
#define IDC_BUTTON_TOOTH_SwapEdge_SharpEdge 1699
#define IDC_BUTTON_TOOTH_PathSmooth     1700
#define IDC_BUTTON_TOOTH_PathProjection 1703
#define IDC_BUTTON_CHECKTEETH           1704
#define IDC_BUTTON_FIXGAP               1705
#define IDC_BUTTON_SEWING               1706
#define IDC_BUTTON_ACIS_TWOSURFACE      1707
#define ID_VIEW_FORMVIEW1               32771
#define ID_VIEW_FORMVIEW2               32772
#define ID_VIEW_EDITVIEW                32773
#define ID_VIEW_LISTVIEW                32774
#define ID_VIEW_SPLITTER                32775
#define ID_ADD_FORM_VIEW                32776
#define ID_REMOVE_FORM_VIEW             32777
#define ID_MESH_COLOR_HEIGHT            32778
#define ID_WIMP                         32781
#define IDM_MICROSOFT_HOME              32782
#define ID_MICROSOFT_HOME               32783
#define ID_MAP_TO_NURBSSURF             32784
#define ID_MENUITEM32785                32785
#define ID_MENUITEM32786                32786
#define ID_MENUITEM32787                32787
#define ID_LINEINPARAMETER              32788
#define ID_MENUITEM32789                32789
#define ID_MENUITEM32790                32790
#define ID_MENUITEM32791                32791
#define ID_MENUITEM32792                32792
#define ID_MENUITEM32793                32793
#define ID_Menu                         32794
#define ID_SURFACE_1                    32795
#define ID_SURFACE_SHOWPARAMETER        32796
#define ID_SURFACE_SHOWCOLORBOUNDARY    32797
#define ID_SURFACE_SHOWISOPARAMETERCURVES 32798
#define ID_SURFACE_SHOWSUBDIVISIONCURVES 32799
#define ID_SURFACE_SHOWSURFACE          32800
#define ID_SURFACE_ONLYSHOWME           32801
#define ID_SURFACE_SHOWOPTIMALISOPARAMETERCURVES 32802
#define ID_SURFACE_TRANSFORMATIONOFMOBIUS 32803
#define ID_SURFACE_TRANSFORMATIONOFMOBIUSANDBILINEAR 32804
#define ID_SURFACE_TRANSFORMATIONOFMOBIUSANDCUBIC 32805
#define ID_SURFACE_SHOWSUBSURFACECOORDINATE 32806
#define ID_RENDER_SETRENDERMODE         32807
#define ID_SURFACE_MOBIUS               32808
#define ID_SURFACE_POVRAY               32809
#define ID_                             32810
#define ID_SURFACE_NORMALIZE            32811
#define ID_SURFACE_SAVEAS               32812
#define ID_SURFACE_SHOWCONTROLPOINTNETWORK 32813
#define ID_SURFACE_SHOWBILINEARCOEFFICIENTS 32814
#define ID_RENDER_SETREND               32815
#define ID_SURFACE_SHOWCOORDINATEAXIS   32816
#define ID_SAVEASTMFILE                 32817
#define ID_SURFACE_SHOWOPTIMALAREAPRESERVING 32818
#define ID_SURFACE_SHOWOPTIMALAREAPRESERVINGMODIFIED 32819
#define ID_SURFACE_SHOWCOLORORTHOGONALITY 32820
#define ID_SURFACE_SHOWORIGINALCOLOR    32821
#define ID_MESH_GENERATEBSPINESURFACE   32822
#define ID_MESH_GENERATEOPTIMALBILINEARTRANSFORMATION 32823
#define ID_BsplineFITTINGERROR          32824
#define ID_GL_ADD_WIREFRAME             32825
#define ID_GL_SMOOTH                    32826
#define ID_MESH_LOOP                    32827
#define ID_GL_LINE                      32828
#define ID_GL_VERTEX                    32829
#define ID_GL_FACE                      32830
#define ID_GL_LIGHT                     32831
#define ID_SURFACE_SHOWTRANSFORMEDPARAMETERDOMAIN 32832
#define ID_MESH_GENERATEQUADMESH        32833
#define ID_SURFACE_SHOWGENERALBILINEARISOPARAMETERCURVES 32835
#define ID_SURFACE_CONVERTTOTSPLINE     32836
#define ID_TSPLINE_PLOTPREIMAGE         32837
#define ID_MESH_SHOWEDGE                32838
#define ID_MESH_SHOWVERTEX              32839
#define IDC_ShowCoordinateAxis_Object   32840
#define ID_CURVE_SHOWCONTROLPOINTS      32841
#define ID_SURFACE_COMPUTECONFORMALENERGY 32842
#define ID_ACTIONS_KILLCURRENTT         32843
#define ID_MESH_SHOWFACE                32844
#define ID_TSPLINE_SAVEAS               32845
#define ID_MESH_NORMALIZE               32846
#define ID_MESH3D_NORMALIZE             32847
#define ID_MESH_SAVEASMFILE             32848
#define ID_MESH_SHOWLANDMARK            32849
#define ID_MESH_SHOWLANDMARKEDGE        32851
#define ID_MESH_SHOWLANDMARKVERTEX      32852
#define ID_MESH_SHOWVERTEXINDEX         32853
#define ID_MESH_SHOWEDGEINDEX           32854
#define ID_MESH_SHOWSHARPEDGEINDEX      32855
#define ID_MESH_SHOWSELECTEDLANDMARK    32856
#define ID_MESH_SHOWSELECTEDSHARPEDGE   32857
#define ID_MESH_SHOWSHARPEDGE           32858
#define ID_STATE_TEXT                   32859
#define ID_MESH_SHOWSELECTEDV           32859
#define ID_MESH_SHOWSELECTEDVERTEX      32860
#define ID_MESH_SHOWSELECTEDVERTE       32861
#define ID_MESH_SHOWFACEAREA            32862
#define ID_MESH_SHOW                    32863
#define ID_MESH_SHOWTargetFaceArea      32864
#define ID_MESH_SHOWAREADIFFERENCE      32865
#define ID_MESH_SHOWXYINDEX             32866
#define ID_MESH_SHOWLANDMARK32867       32867
#define ID_MESH_SHOWLANDMARKINDEX       32868
#define ID_MESH_SHOWMERGECONSTRAINTS    32869
#define ID_MESH_SHOWUNIFORMGRID         32870
#define ID_MESH_SHOWDISTRICTINDEX       32871
#define ID_MESH_SHOWJIANZHI             32872
#define ID_MESH_SHOWSTATENAME           32873
#define ID_ShowPuzzleGraph              32876
#define ID_MESH_SETCOLORRS              32877
#define ID_MESH_SHOWVERTEXMU            32878
#define ID_MESH_SHOWTRIANGLEMU          32879
#define ID_MESH_SHOWVERTEXMUVECTORFIELD 32882
#define ID_MESH_SHOWVECTORDISPLACEMENT  32883
#define ID_MESH_SHOWSELECTEDFACE        32884
#define ID_MESH_SHOWSHARPSELECTEDVERTEX 32885
#define ID_MESH_SHOWC                   32886
#define ID_MESH_SHOWCELLXYINDEX         32887
#define ID_MESH_SHOWMESHINFORMATION     32888
#define ID_MESH_EXTRACTPARAMETERDOMAIN  32889
#define ID_MESH_SETCURRENTMESH          32890
#define IDC_Omino_SetCurrentMesh_Menu   32891
#define ID_MESH_ZOOMALL                 32892
#define ID_MESH_ZOOMTOFITCURRENTMESH    32893
#define ID_MENU_MESH_ZOOMALL            32894
#define ID_MENU_ZOO_CURRENTMESH_TOFIT   32895
#define ID_MENU_ZOOM_CURRENTMESH_TOFIT  32896
#define ID_ZoomAllToFitCurrentMesh      32897
#define ID_MESH_SHOWFACEINDEX           32898
#define ID_MESH_SHOWSELECTEDVERTEXINDEX 32899
#define ID_MESH_SHOWFEATUREVERTEX       32900
#define ID_MESH_SHOWFEATUREVERTEXINDEX  32901
#define ID_POLYGON_SHOWPOLYGONLINE      32902
#define ID_POLYGON_SHOWPOLYGONINDEX     32903
#define ID_POLYGON_SHOWPOLYGONINNERRINGS 32904
#define ID_POLYGON_DELETE               32905
#define IDS_NEW_SWITCH_SPLIT_FILE       61204
#define IDS_CANNOT_CREATE_NEW_SWITCHSPLIT 61205
#define ID_PROGRESS                     61206
#define IDC_PROGRESS                    61207
#define ID_SURFACE_DELETE               61208
#define ID_ZOOM_ZOOMALL                 61209
#define ID_SURFACE_SUBDIVIDE            61210
#define ID_SURFACE_SHOWSURFACEINFORMATION 61211
#define ID_SURFACE_SHOWISOLINE          61212
#define ID_SURFACE_SHOWMOBIUSANDBILINEAR 61213
#define ID_MESH_SHOWRECT                61234
#define ID_MESH_SHOWRECTILINEARGRID     61235
#define ID_MESH_SHOWSHARPEDGEBASENUM    61236
#define ID_MESH_SHOWEDGEINDEX61237      61237
#define ID_MESH_S                       61238
#define ID_MESH_SHOWLANDMARKENDVERTEXINDEX 61239
#define ID_MESH_SHOWSHARPEDGE61240      61240
#define ID_SHOWSHARPEDGE_1              61241
#define ID_MESH_SHOWANCHORPOINTS        61242
#define ID_MESH_SHOWSELECTEDEDGE        61243
#define ID_MESH_SHOWPOINTSONSURFACE     61244
#define ID_MESH_SHOWPOINTS_ONSURFACE    61245
#define ID_MESH_ONLYMOVEME              61246
#define ID_MORE                         61247

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        232
#define _APS_NEXT_COMMAND_VALUE         61248
#define _APS_NEXT_CONTROL_VALUE         1698
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
